modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/latvian-dev/ProjectEX/issues"
license = "GNU LGPLv3"

[[mods]]
modId = "projectex"
version = "${file.jarVersion}"
displayName = "ProjectEX"
authors = "LatvianModder"
description = '''
An addon to ProjectE
'''
logoFile = "projectex_logo.png"

[[dependencies.projectex]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.projectex]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.projectex]]
modId = "projecte"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
